/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acc;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Laci
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        myACC = new ACC();
        wheelStateInDegrees = currentSpeed = targetSpeed = 0;
        nearestObstacleDistance = 50;
    }

    public IACC myACC;
    public boolean ACCState;

    int wheelStateInDegrees;
    int currentSpeed;
    int targetSpeed;
    int nearestObstacleDistance;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        SliderWheel = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        SliderSpeed = new javax.swing.JSlider();
        SliderObstacleDistance = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelState = new javax.swing.JLabel();
        SliderTargetSpeed = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SliderWheel.setMajorTickSpacing(1);
        SliderWheel.setMaximum(45);
        SliderWheel.setMinimum(-45);
        SliderWheel.setPaintLabels(true);
        SliderWheel.setPaintTicks(true);
        SliderWheel.setValue(0);
        SliderWheel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderWheelStateChanged(evt);
            }
        });

        jLabel1.setText("Wheel steering [°]");

        SliderSpeed.setMajorTickSpacing(5);
        SliderSpeed.setMaximum(200);
        SliderSpeed.setPaintLabels(true);
        SliderSpeed.setPaintTicks(true);
        SliderSpeed.setValue(0);
        SliderSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderSpeedStateChanged(evt);
            }
        });

        SliderObstacleDistance.setMajorTickSpacing(5);
        SliderObstacleDistance.setPaintLabels(true);
        SliderObstacleDistance.setPaintTicks(true);
        SliderObstacleDistance.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderObstacleDistanceStateChanged(evt);
            }
        });

        jLabel2.setText("Speed [km/h]");

        jLabel3.setText("Nearest object distance [m]");

        LabelState.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelState.setText("Do nothing!!!");

        SliderTargetSpeed.setMajorTickSpacing(5);
        SliderTargetSpeed.setMaximum(200);
        SliderTargetSpeed.setPaintLabels(true);
        SliderTargetSpeed.setPaintTicks(true);
        SliderTargetSpeed.setValue(0);
        SliderTargetSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderTargetSpeedStateChanged(evt);
            }
        });

        jLabel4.setText("Target speed [km/h]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderWheel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SliderObstacleDistance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SliderTargetSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addComponent(SliderSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(LabelState, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderTargetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderObstacleDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(SliderWheel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderSpeedStateChanged
        // TODO add your handling code here:
        currentSpeed = SliderSpeed.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderSpeedStateChanged

    private void SliderObstacleDistanceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderObstacleDistanceStateChanged
        // TODO add your handling code here:
        nearestObstacleDistance = SliderObstacleDistance.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderObstacleDistanceStateChanged

    private void SliderWheelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderWheelStateChanged
        // TODO add your handling code here:
        wheelStateInDegrees = SliderWheel.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderWheelStateChanged

    private void SliderTargetSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderTargetSpeedStateChanged
        targetSpeed = SliderTargetSpeed.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderTargetSpeedStateChanged

    private void ChangeLabel() {
        myACC.PedalState(wheelStateInDegrees, currentSpeed, targetSpeed, nearestObstacleDistance);
        int temp = myACC.getPedal();
        switch (temp) {
            case 1:
                LabelState.setText("Throttling!!!");
                break;
            case 0:
                LabelState.setText("Do nothing!!!");
                break;
            default:
                LabelState.setText("Breaking!!!");
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelState;
    private javax.swing.JSlider SliderObstacleDistance;
    private javax.swing.JSlider SliderSpeed;
    private javax.swing.JSlider SliderTargetSpeed;
    private javax.swing.JSlider SliderWheel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
